import { Heder } from '@/componenet/Heder'
import Navbar from '@/componenet/Navbar'
import './globals.css'
import Providers from './Providers'
import SerchBox from '@/componenet/SerchBox'

export const metadata = {
  title: 'create IMDb project',
  description: 'Generated by Ehsan Madadi',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
        <Heder/>
        <SerchBox/>
        <Navbar/>
        {children}
        </Providers>
        </body>
    </html>
  )
}
